require("config.options")
require("config.keymaps")
require("config.lazy")
require("config.lsp")
require("config.transparency")
vim.cmd.colorscheme("rose-pine")
vim.opt.shortmess:append("I")
vim.keymap.set("n", "<F5>", ":!python %<CR>", { desc = "Run Python file" })
